--------------------
-- TABLE CREATION --
--------------------

-- CREDIT CARD TABLE 
CREATE TABLE CREDIT_CARD(
	CREDIT_CARD_NO			VARCHAR(20) PRIMARY KEY,
	CREDIT_CARD_FNAME		VARCHAR(30),
	CREDIT_CARD_LNAME		VARCHAR(30),
	CREDIT_EXPIRE_DATE		VARCHAR(10),
	CREDIT_SEC_CODE			INT
 );

-- CUSTOMER TABLE 
CREATE TABLE CUSTOMER(
	CUST_ID                 SERIAL PRIMARY KEY,
	CUST_FNAME              VARCHAR(30),
	CUST_LNAME              VARCHAR(30),
	CUST_PHONE              VARCHAR(15),
	CUST_BALANCE            DECIMAL(8,2),
	CUST_CREDIT_CARD_NO     VARCHAR(20)
);


-- TRANSACTION TABLE 
CREATE TABLE TRANSACTIONS (
	TRANS_NO				SERIAL PRIMARY KEY,
	TRANS_DATE				DATE,
	TRANS_AMT				DECIMAL(8,2),
	TRANS_RES_ID			INT
);


-- EMPLOYEE TABLE 
CREATE TABLE EMPLOYEE (
	EMP_ID					SERIAL PRIMARY KEY,
	EMP_FNAME				VARCHAR(30),
	EMP_LNAME				VARCHAR(30),
	EMP_TITLE				VARCHAR(25),
	EMP_LOC_ID				INT,
	SUPER_ID				INT, 
	EMP_SSN					INT
);

-- LOCATION TABLE
CREATE TABLE LOCATION (
    LOC_ID					SERIAL PRIMARY KEY,
    LOC_HOURS				VARCHAR(200), 
    LOC_ADDRESS				VARCHAR(50),
    LOC_PHONE				VARCHAR(15),
    LOC_NAME				VARCHAR(50),
    LOC_SUPER_ID			INT 
);


-- RESERVATION TABLE 
CREATE TABLE RESERVATION (
    RES_NO					SERIAL PRIMARY KEY,     
    RES_EMP_ID				INT, 
    RES_CUST_ID				INT, 
    RES_LOC_ID				INT, 
    RES_ROOM_NO				INT, 
    RES_START_DATE			DATE,
    RES_END_DATE			DATE
);


-- ROOM_TYPE TABLE
CREATE TABLE ROOM_TYPE(
    TYPE_CODE				SERIAL PRIMARY KEY,     
    TYPE_PRICE				DECIMAL(6,2),
    TYPE_DESCRIPTION		VARCHAR(4000)
);


-- ROOM TABLE
CREATE TABLE ROOM (
    ROOM_NO					INT PRIMARY KEY,     
    ROOM_LOC				INT,
    ROOM_TYPE				INT,
    ROOM_AVAILABLE			VARCHAR(1)
);
