-- Comment following line to execute script
SET NOEXEC ON GO

--------------------
-- TABLE CREATION --
--------------------

-- CREDIT CARD TABLE 
CREATE TABLE CREDIT_CARD(
	CREDIT_CARD_NO			NVARCHAR(20) PRIMARY KEY,
	CREDIT_CARD_FNAME		NVARCHAR(30),
	CREDIT_CARD_LNAME		NVARCHAR(30),
	CREDIT_EXPIRE_DATE		NVARCHAR(10),
	CREDIT_SEC_CODE			INT,
 );

-- CUSTOMER TABLE 
CREATE TABLE CUSTOMER(
	CUST_ID                 INT IDENTITY(1,1) PRIMARY KEY,
	CUST_FNAME              NVARCHAR(30),
	CUST_LNAME              NVARCHAR(30),
	CUST_PHONE              NVARCHAR(15),
	CUST_BALANCE            DECIMAL(8,2),
	CUST_CREDIT_CARD_NO     NVARCHAR(20),
);


-- TRANSACTION TABLE 
CREATE TABLE TRANSACTIONS (
	TRANS_NO				INT IDENTITY (1,1) PRIMARY KEY,
	TRANS_DATE				DATE,
	TRANS_AMT				DECIMAL(8,2),
	TRANS_RES_ID			INT,
);


-- EMPLOYEE TABLE 
CREATE TABLE EMPLOYEE (
	EMP_ID					INT IDENTITY(1,1) PRIMARY KEY,
	EMP_FNAME				NVARCHAR(30),
	EMP_LNAME				NVARCHAR(30),
	EMP_TITLE				NVARCHAR(25),
	EMP_LOC_ID				INT,
	SUPER_ID				INT, 
	EMP_SSN					INT,
);

-- LOCATION TABLE
CREATE TABLE LOCATION (
    LOC_ID					INT IDENTITY(1,1) PRIMARY KEY,
    LOC_HOURS				NVARCHAR(200), 
    LOC_ADDRESS				NVARCHAR(50),
    LOC_PHONE				NVARCHAR(15),
    LOC_NAME				NVARCHAR(50),
    LOC_SUPER_ID			INT 
);


-- RESERVATION TABLE 
CREATE TABLE RESERVATION (
    RES_NO					INT IDENTITY(1,1) PRIMARY KEY,     
    RES_EMP_ID				INT, 
    RES_CUST_ID				INT, 
    RES_LOC_ID				INT, 
    RES_ROOM_NO				INT, 
    RES_START_DATE			DATE,
    RES_END_DATE			DATE
);


-- ROOM_TYPE TABLE
CREATE TABLE ROOM_TYPE(
    TYPE_CODE				INT IDENTITY (1,1) PRIMARY KEY,     
    TYPE_PRICE				DECIMAL(6,2),
    TYPE_DESCRIPTION		NVARCHAR(4000)
);


-- ROOM TABLE
CREATE TABLE ROOM (
    ROOM_NO					INT PRIMARY KEY,     
    ROOM_LOC				INT,
    ROOM_TYPE				INT,
    ROOM_AVAILABLE			NVARCHAR(1)
);

-----------------
-- CONSTRAINTS --
-----------------

-- CUSTOMER CONSTRAINTS 
ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_CREDIT_CARD FOREIGN KEY (CUST_CREDIT_CARD_NO) -- CUSTOMER -> CREDIT CARD
	REFERENCES CREDIT_CARD (CREDIT_CARD_NO);

-- TRANSACTIONS CONSTRAINTS
ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_TRANSACTIONS_RESERVATION FOREIGN KEY (TRANS_RES_ID) -- TRANSACTIONS -> RESERVATION
	REFERENCES RESERVATION (RES_NO),
CONSTRAINT CHK_TRANS_LIMIT CHECK (TRANS_AMT < 1000000); -- BUSINESS CONSTRAINT

-- EMPLOYEE CONSTRAINTS 
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_LOCATION FOREIGN KEY (EMP_LOC_ID) -- EMPLOYEE -> LOCATION
	REFERENCES LOCATION (LOC_ID),
CONSTRAINT FK_EMPLOYEE_EMPLOYEE FOREIGN KEY (SUPER_ID) -- EMPLOYEE -> EMPLOYEE
	REFERENCES EMPLOYEE (EMP_ID);

-- LOCATION CONSTRAINTS 
ALTER TABLE LOCATION
ADD CONSTRAINT FK_LOCATION_EMPLOYEE FOREIGN KEY (LOC_SUPER_ID) -- LOCATION -> EMPLOYEE
	REFERENCES EMPLOYEE (EMP_ID);

-- RESERVATION CONSTRAINTS 
ALTER TABLE RESERVATION
ADD CONSTRAINT FK_RESERVATION_EMPLOYEE FOREIGN KEY (RES_EMP_ID) -- RESERVATION -> EMPLOYEE
	REFERENCES EMPLOYEE (EMP_ID),
CONSTRAINT FK_RESERVATION_CUSTOMER FOREIGN KEY (RES_CUST_ID) -- RESERVATION -> CUSTOMER
	REFERENCES CUSTOMER (CUST_ID),
CONSTRAINT FK_RESERVATION_LOCATION FOREIGN KEY (RES_LOC_ID) -- RESERVATION -> LOCATION
	REFERENCES LOCATION (LOC_ID),
CONSTRAINT FK_RESERVATION_ROOM FOREIGN KEY (RES_ROOM_NO) -- RESERVATION -> ROOM
	REFERENCES ROOM (ROOM_NO);


-- ROOM CONSTRAINTS
ALTER TABLE ROOM
ADD CONSTRAINT FK_ROOM_LOCATION FOREIGN KEY (ROOM_LOC) -- ROOM -> LOCATION
	REFERENCES LOCATION (LOC_ID),
CONSTRAINT FK_ROOM_ROOM_TYPE FOREIGN KEY (ROOM_TYPE) -- ROOM -> ROOM TYPE
	REFERENCES ROOM_TYPE (TYPE_CODE);